// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package registry

import (
	"github.com/greendrop/todo-graphql-go-sample/infrastructure/persistence"
	"github.com/greendrop/todo-graphql-go-sample/interface/graph"
	"github.com/greendrop/todo-graphql-go-sample/usecase/todo"
	"github.com/greendrop/todo-graphql-go-sample/usecase/user"
)

// Injectors from wire.go:

func InitializeGraphResolver() *graph.Resolver {
	todoRepository := persistence.NewTodoPersistence()
	todoGetTodoListUseCase := usecase_todo.NewTodoGetTodoListUseCase(todoRepository)
	todoCreateTodoUseCase := usecase_todo.NewTodoCreateTodoUseCase(todoRepository)
	userRepository := persistence.NewUserPersistence()
	userGetUserUseCase := usecase_user.NewUserGetUserUseCase(userRepository)
	resolver := graph.NewResolver(todoGetTodoListUseCase, todoCreateTodoUseCase, userGetUserUseCase)
	return resolver
}
